spring.application.name=personal_blog


spring.datasource.url=jdbc:h2:file:./data/blogdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#database in memory using H2
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.path=/h2-console